local settings = {
    -- every line should be same width without escaped \
    header = {
        type = "text",
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 1,
        content = {
            [[▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄]],
            [[█ / __ \ \__/ / __ \ \__/ / __ \ \__/ / __ \ \__/ / __ \ \__/ / █]],
            [[█/ /  \ \____/ /  \ \____/ /  \ \____/  \ \____/ /  \ \____/ /█]],
            [[█\ \__/◢███████████/ __ █████/ __ \██/ / __ \ \__/ / __ \ \█]],
            [[█ \___◢███  \████ /  \ █████/ \ \____/ /  \ \____/ /  \ \ █]],
            [[█ / _◢████__/ /   \█████████████ ███ \ ███████████/ / █]],
            [[█/ / ███████████ ██_██████████ █████ ██████████████_/ /█]],
            [[█\ \__/ / __██████__ █████████ █████ █████ ████ █████ \ \█]],
            [[█ \████/  ██████  \█████████ █████ █████ ████ █████ \ █]],
            [[█ /███████████/████████████████ █████ █████ ████ ██████/ █]],
            [[█/ /  \ \____/ /  \ \____/ /  \ \____/ /  \ \____/ /  \ \____/ /█]],
            [[▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀]],
        },
        highlight = "Statement",
        default_color = "#619D3D",
        oldfiles_amount = 0,
    },
    maptitle = {
        type = "text",
        align = "center",
        fold_section = false,
        title = "Map Title",
        margin = 5,
        content = {
            " Find File",
            " Recent Files",
            " Colorschemes",
            " Mason",
            " Terminal",
            " New File",
            "󰍉 Find Word",
            "󰌓 Cheatsheet",
            "󰒲 Lazy",
            "󰈭 Word Info",
            "󰿅 Quit",
        },
        highlight = "Statement",
        default_color = "#619D3D",
        oldfiles_amount = 0,
    },
    body = {
        type = "mapping",
        align = "center",
        fold_section = false,
        title = "Basic Commands",
        margin = 2,
        content = {
            { " Find File", "Telescope find_files", "f" },
            { " Recent Files", "Telescope oldfiles", "r" },
            { " Colorschemes", "Telescope colorscheme", "c" },
            { " Mason", "Mason", "m" },
            { " Terminal", "ToggleTerm size=40 dir=~ direction=horizontal name=home", "t" },
            { " New File", "lua require'startup'.new_file()", "n" },
            { "󰍉 Find Word", "Telescope live_grep", "g" },
            { "󰌓 Cheatsheet", "Cheatsheet", "s" },
            { "󰒲 Lazy", "Lazy", "l" },
            { "󰈭 Word Info", "lua require'startup'.word_info()", "w" },
            { "󰿅 Quit", "quit", "q" },
        },
        highlight = "String",
        default_color = "",
        oldfiles_amount = 0,
    },
    body_2 = {
        type = "oldfiles",
        oldfiles_directory = true,
        align = "center",
        fold_section = true,
        title = "Oldfiles of Directory",
        margin = 2,
        content = {},
        highlight = "String",
        default_color = "#FFFFFF",
        oldfiles_amount = 10,
    },
    footer = {
        type = "text",
        oldfiles_directory = false,
        align = "left",
        fold_section = false,
        title = "Quote",
        margin = 5,
        content = require("startup.functions").quote(),
        highlight = "Constant",
        default_color = "",
        oldfiles_amount = 0,
    },
    clock = {
        type = "text",
        content = {   " " .. os.date("%A, %d-%m-%y | %H:%M")},
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "",
        margin = 5,
        highlight = "TSString",
        default_color = "#FFFFFF",
        oldfiles_amount = 10,
    },

    options = {
        after = function()
            require("startup.utils").oldfiles_mappings()
        end,
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 0, 1, 2, 2, 1, },
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = {
        "header",
        "clock",
        "body",
        "body_2",
        "footer",
    },
}
return settings
